server:
  port: 8762
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  application:
    name: servidor-gateway
  cloud:
    gateway:
      routes:
        - id: service-users
          uri: lb://service-users
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2
        - id: server-autorization
          uri: lb://server-autorization
          predicates:
            - Path=/api/security/**
          filters:
            - StripPrefix=2
  security:
    oauth2:
      client:
        provider:
          spring:
            issuer-uri: http://localhost:9000
        registration:
          client:
            provider: spring
            client-id: libreria
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8762/login/oauth2/code/libreria
            scope: profile,openid
            client-name: login spring provider
            client-authentication-method: client_secret_basic
