version: "3.8"
services:
	eureka-server:
		build: Infraestructura/eureka-server/.
		image: servidor-eureka
		ports:
		    -	"8761:8761"
		environment:
			- JAVA_OPTS=
				-Xms256M
				-Xms256M
	servidor-gateway:
		build: Infraestructura/servidor-gateway/.
		image: servidor-gateway
		ports:
		    -   "8762:8762"
		environment:
			- JAVA_OPTS=
				-Xms256M
				-Xms256M
				-EUREKA-SERVER=http://eureka-server:8762/eureka
		depends_on:
		    -   eureka-server
	servidor-admin:
		build: Infraestructura/AdminServer/.
		image: servidor-admin
		ports:
		    -   "8763:8763"
		environment:
			- JAVA_OPTS=
				-Xms256M
				-Xms256M
				-EUREKA-SERVER=http://eureka-server:8762/eureka
		depends_on:
			- eureka-server
			- servidor-gateway
	servidor-oauth:
		build: Seguridad/Autorization-server/.
		image: servidor-oauth
		ports:
		    -   "9000:9000"
		environment:
			- JAVA_OPTS=
				-Xms256M
				-Xms256M
				-EUREKA-SERVER=http://eureka-server:8762/eureka
		depends_on:
			- eureka-server
			- servidor-admin
			- servidor-gateway
	servicio-usuarios:
		build: DominioNegocio/service-users/.
		image: servicio-usuario
		environment:
			- JAVA_OPTS=
				-Xms256M
				-Xms256M
				-EUREKA-SERVER=http://eureka-server:8762/eureka
				-PORT=5001
		depends_on:
			- eureka-server
			- servidor-oauth
			- servidor-gateway
			- servidor-admin
	servicio-libros:
		build: DominioNegocio/service-books/.
		image: servicio-libros
		environment:
			- JAVA_OPTS=
				-Xms256M
				-Xms256M
				-EUREKA-SERVER=http://eureka-server:8762/eureka
				-PORT=5002
		depends_on:
			- eureka-server
			- servidor-admin
			- servidor-oauth
			- servidor-gateway
			- servicio-usuarios