services:
  servidor-eureka:
    build: Infraestructura/eureka-server
    image: servidor-eureka
    ports:
      - "8761:8761"
    environment:
      JAVA_OPTS: "-Xms256M -Xmx256M"
      PORT: "8761"
    restart: unless-stopped

  servidor-gateway:
    build: Infraestructura/getway-server
    image: servidor-gateway
    ports:
      - "8762:8762"
    environment:
      JAVA_OPTS: "-Xms256M -Xmx256M"
      PORT: "8762"
      EUREKA_SERVER: "http://servidor-eureka:8761/eureka"
      EUREKA-SERVER: "http://servidor-eureka:8761/eureka"
    depends_on:
      - servidor-eureka
    restart: unless-stopped

  servidor-admin:
    build: Infraestructura/admin-server
    image: servidor-admin
    ports:
      - "8763:8763"
    environment:
      JAVA_OPTS: "-Xms256M -Xmx256M"
      PORT: "8763"
      EUREKA_SERVER: "http://servidor-eureka:8761/eureka"
      EUREKA-SERVER: "http://servidor-eureka:8761/eureka"
    depends_on:
      - servidor-eureka
    restart: unless-stopped

  service-auth:
    build: Seguridad/Autorization-server
    image: servidor-authorization
    ports:
      - "9000:9000"
    environment:
      JAVA_OPTS: "-Xms256M -Xmx256M"
      PORT: "9000"
      EUREKA_SERVER: "http://servidor-eureka:8761/eureka"
      EUREKA-SERVER: "http://servidor-eureka:8761/eureka"
    depends_on:
      - servidor-eureka
    restart: unless-stopped

  service-usuarios:
    build: DominioNegocio/service-users
    image: servidor-usuarios
    ports:
      - "4000:4000"
    environment:
      JAVA_OPTS: "-Xms256M -Xmx256M"
      PORT: "4000"
      EUREKA_SERVER: "http://servidor-eureka:8761/eureka"
      EUREKA-SERVER: "http://servidor-eureka:8761/eureka"
    depends_on:
      - servidor-eureka
    restart: unless-stopped

  service-libros:
    build: DominioNegocio/service-books
    image: servicio-libros
    ports:
      - "4001:4001"
    environment:
      JAVA_OPTS: "-Xms256M -Xmx256M"
      PORT: "4001"
      EUREKA_SERVER: "http://servidor-eureka:8761/eureka"
      EUREKA-SERVER: "http://servidor-eureka:8761/eureka"
    depends_on:
      - servidor-eureka
    restart: unless-stopped
