apiVersion: apps/v1
kind: Deployment
metadata:
   name: bb-demo #Nombre de como queda stanciado en dkubernetes
   namespace: default  #namespace donde esta se alojara el servicio
spec:
   replicas: 1 # cantidad de replicas que se tienen 
   selector:
      matchLabels:
         bb: web ## nonbres del los servicios
   template:
      metadata:
         labels:
            bb: web 
      spec:
         containers:
            - name: demo  # nombre de la imagen en kubernates 
              image: demo # nombre de la imagen en docker
              imagePullPolicy: Never # el parametro never dice que la imagen es local y no es necesario  que se base de docker hub
---
apiVersion: v1
kind: Service
metadata:
   name: bb-entrypoint #entrypont decide el endpoint que se va a tener 
   namespace: default
spec:
   type: NodePort  ## no del puerto 
   selector:
      bb: web
   ports:
      - port: 8080    #puerto por donde se expone al imgagen 
        targetPort: 8080 # puerto por donde se va a exponer la imagen 
        nodePort: 30001 # puerto del nodo para salida del nodo 