name: CI/CD Java con Git Flow

on:
  pull_request:
    branches: [ "develop" ]
  push:
    tags:
      - 'v*.*.*'

jobs:
  verify-build:
    runs-on: ubuntu-latest
    environment: develop
    env:
      JDBC_URL: ${{ secrets.JDBC_URL }}
      JDBC_USERNAME: ${{ secrets.JDBC_USERNAME }}
      JDBC_PASSWORD: ${{ secrets.JDBC_PASSWORD }}
      EUREKA_SERVER: ${{ secrets.EUREKA_SERVER }}
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Compilar y verificar
        run: mvn -B clean verify --file pom.xml

      - name: Cobertura de código
        run: mvn test jacoco:report jacoco:check

      - name: Bump versión semántica
        uses: paulhatch/semantic-version@v5.0.3
        id: version
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          patch_pattern: "(PATCH)"
          default: patch

      - name: Actualizar versión en pom.xml
        run: |
          echo "Actualizando versión en pom.xml a ${{ steps.version.outputs.version }}"
          mvn versions:set -DnewVersion=${{ steps.version.outputs.version }}
          mvn versions:commit

      - name: Crear release automático
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: "Release develop ${{ steps.version.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-master:
    runs-on: ubuntu-latest
    environment: production
    env:
      JDBC_URL: ${{ secrets.JDBC_URL_PROD }}
      JDBC_USERNAME: ${{ secrets.JDBC_USERNAME_PROD }}
      JDBC_PASSWORD: ${{ secrets.JDBC_PASSWORD_PROD }}
      EUREKA_SERVER: ${{ secrets.EUREKA_SERVER_PROD }}
      MYSQL_HOST: ${{ secrets.MYSQL_HOST_PROD }}
      MYSQL_PORT: ${{ secrets.MYSQL_PORT_PROD }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE_PROD }}
      MYSQL_USER: ${{ secrets.MYSQL_USER_PROD }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD_PROD }}

    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - name: Compilar en master
        run: mvn -B clean verify --file pom.xml
      - name: Publicar release estable
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release estable ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
